[build]
  command = "npm run build"
  publish = "dist/client"

[functions]
  directory = "netlify/functions"


# Enable Netlify Build Plugins
[[plugins]]
package = "@netlify/plugin-sitemap"

[[plugins]]
package = "@netlify/plugin-minify-html"

[[plugins]]
package = "@netlify/plugin-lighthouse"

[[plugins]]
package = "@netlify/plugin-a11y"

[[plugins]]
package = "@netlify/plugin-snyk"
